.TH GETHDRS "1" "Apr 2020" "gethdrs VERSION" "User Commands"
.SH NAME
.PP
gethdrs \- Trace HTTP and HTTPS responses
.SH SYNOPSIS
.PP
.B gethdrs
.br
.B gethdrs
[\FIOPTIONS\fR]
.I URL
.br
.B gethdrs \-h
.SH DESCRIPTION
The program
.B gethdrs
is intended as an aid for debugging web servers or web-based applications.
It provides a listing of headers and possibly data that constitute the
response to an HTTP request. For complex cases, such as a
series of HTTP redirects, the intermediate headers are shown, not just
the final ones.
When run with no argument,
.BR gethdrs ,
will run as a desktop application. There is an on-line manual with a
full description of the program available in the application's 'help'
window.
.PP
When run with command-line options, the program will complete a single
HTTP or HTTPS request, print response headers and (if desired) some or
all of the response provided it is one of a number of text-based formats.
.SH OPTIONS
The options are
.TP
.BI \-m\  METHOD
This option sets the HTTP method. The argument
.B METHOD
may be
.BR GET ,
.BR PUT ,
.BR POST ,
or
.BR HEAD .
.TP
.BI \-c\  CHARSET
This option sets the character set for reading data files.
The argument
.B CHARSET
can be the name of any character set recognized by the Java class library.
Typically this will be
.BR UTF-8.
.TP
.BI \-t\  MTYPE
This option sets the media type for data sent in HTTP requests, and
is ignored if the
.B \-u
option is used. The argument MTYPE may be either
.BR application-csh ,
.BR application/json ,
.BR application/x-perl ,
.BR application/x-sh ,
.BR application/x-tcl ,
.BR application/x-tex ,
.BR application/x-troff ,
.BR application/x-troff-man ,
.BR application/x-troff-me ,
.BR application/x-troff-ms ,
.BR application/x-www-form-urlencoded ,
.BR multipart/form-data ,
.BR text/html ,
.BR text/plain ,
or
.BR text/xml .
.TP
.B \-u
This option sets the media type to
.B "application/x-www-form-urlencoded"
and also URL-encodes any data that is provided.
.TP
.BI \-i\  FILE
This option provides that a file name
.I FILE
for data that will be sent in an HTTP request.
.TP
.BI \-h\  FILE
This option provides a file
.I FILE
containing HTTP request headers. The format of this file is described
in a separate manual page
.BR gethdrs (5).
.TP
.B \-p
This options sets proxy preferences based on the default system
properties. If the
.B \-p
is set, the
.B \-P
option must not be set.
.TP
.BI \-P\  FILE
This option sets proxy preferences, and other Java properties,
based on the values provided in
the file
.BR FILE .
The format of this file is described in
.BR gethdrs (5).
 If the
.B \-P
is set, the
.B \-p
option must not be set. If the
.B \-P
option is used and there are no other arguments, the GUI will be
started with the preferences menu disabled.  One use of the -P option
is to set Java properties used to configure where SSL looks for
certificates. These are described in the
.BR gethdrs (5)
portion of the manual and by the on-line help that
.B gethdrs
provides. In particular, when a server uses a self-signed certificate,
a trust store will have to be configured. If there is not a
certificate in the trust store that matches the server's certificate,
gethdrs will print a message for a javax.net.ssl.SSHandshakeException
when attempting to visit/load a web page. The message for this
exception may include the text, "unable to find valid certification
path to requested target," which is not particularly
illuminating. Unfortunately, the documentation for Java's SSL
implementation does not provide a clue as to how to determine that the
problem is a missing or wrong certificate rather than some other
issue.
.TP
.B \-n\ all
.TQ
.BI \-n\  N
This option sets the number
.I N
of lines from the response that will be displayed. The String
.B all
indicates that the full response will be shown. If missing, only
the headers are shown.
.TP
.BI \-C\  TIMEOUT
This option sets a timeout in seconds for establishing a connection
to a server. The timeout is given by the value of the argument
.IR TIMEOUT .
A value of zero indicates an unlimited timeout.
.TP
.BI \-P\  TIMEOUT
This option sets a timeout in seconds for reading data from a server: the
maximum time to wait when no data is currently available.  The timeout is
given by the value of the argument
.IR TIMEOUT .
.PP
Using the
.B \-C and
.B \-P
options is particularly useful when
.B gethdrs
is used in a script (e.g., for running a series of tests) in order to
prevent the script from hanging.
.SH EXIT STATUS
.PP
The exit codes are
.TP
0
for normal termination.
.TP
1
for abnormal termination.
.SH FILES
.B /usr/bin/gethdrs
.B /usr/share/gethdrs/geth.jar
.B /usr/share/doc/gethdrs/copyright
.B /usr/share/doc/gethdrs/changelog.gz
.B /usr/share/doc/gethdrs/changelog.Debian.gz
.SH AUTHOR
Written by Bill Zaumen
.SH COPYRIGHT
Copyright \(co 2019 Bill Zaumen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.PP
.BR gethdrs (5)

\"  LocalWords:  GETHDRS gethdrs HTTPS br FIOPTIONS fR TP CHARSET UTF MTYPE
\"  LocalWords:  csh json perl tcl tex troff www urlencoded html xml
\"  LocalWords:  TQ Zaumen GPLv GPL
